//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] csheet_FantasyGrounds2_pc_3_5 {
            get {
                object obj = ResourceManager.GetObject("csheet_FantasyGrounds2_pc_3_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dndi_4E {
            get {
                object obj = ResourceManager.GetObject("Dndi_4E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeroLab_3_5E {
            get {
                object obj = ResourceManager.GetObject("HeroLab_3_5E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeroLab_SavageWorlds {
            get {
                object obj = ResourceManager.GetObject("HeroLab_SavageWorlds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Copyright (c) 2012, SmiteWorks USA LLC --&gt;
        ///&lt;root version=&quot;3.0&quot; release=&quot;&quot; ccversion=&quot;3.0.5.A&quot;&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PCGen_3_5E {
            get {
                object obj = ResourceManager.GetObject("PCGen_3_5E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Copyright (c) 2012, SmiteWorks USA LLC --&gt;
        ///&lt;spellset&gt;
        ///  &lt;availablelevel0 type=&quot;number&quot;&gt;0&lt;/availablelevel0&gt;
        ///  &lt;availablelevel1 type=&quot;number&quot;&gt;0&lt;/availablelevel1&gt;
        ///  &lt;availablelevel2 type=&quot;number&quot;&gt;0&lt;/availablelevel2&gt;
        ///  &lt;availablelevel3 type=&quot;number&quot;&gt;0&lt;/availablelevel3&gt;
        ///  &lt;availablelevel4 type=&quot;number&quot;&gt;0&lt;/availablelevel4&gt;
        ///  &lt;availablelevel5 type=&quot;number&quot;&gt;0&lt;/availablelevel5&gt;
        ///  &lt;availablelevel6 type=&quot;number&quot;&gt;0&lt;/availablelevel6&gt;
        ///  &lt;availablelevel7 type=&quot;number&quot;&gt;0&lt;/availab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpellsetPF {
            get {
                return ResourceManager.GetString("SpellsetPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;!-- Copyright (c) 2012, SmiteWorks USA LLC --&gt;
        ///&lt;root version=&quot;3.0&quot; ccversion=&quot;3.0.5.A&quot;&gt;
        ///  &lt;character&gt;
        ///    &lt;actionpoints type=&quot;number&quot;&gt;1&lt;/actionpoints&gt;
        ///    &lt;attacks&gt;
        ///      &lt;base&gt;
        ///        &lt;total type=&quot;number&quot;&gt;0&lt;/total&gt;
        ///      &lt;/base&gt;
        ///      &lt;melee&gt;
        ///        &lt;misc type=&quot;number&quot;&gt;0&lt;/misc&gt;
        ///        &lt;temporary type=&quot;number&quot;&gt;0&lt;/temporary&gt;
        ///        &lt;total type=&quot;number&quot;&gt;0&lt;/total&gt;
        ///      &lt;/melee&gt;
        ///      &lt;ranged&gt;
        ///        &lt;misc type=&quot;number&quot;&gt;0&lt;/misc&gt;
        ///        &lt;temporary type=&quot;number&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_4E {
            get {
                return ResourceManager.GetString("Template_4E", resourceCulture);
            }
        }
    }
}
